# Generated by Django 3.1.2 on 2020-11-27 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20201107_1738'),
    ]

    operations = [
        migrations.AlterField(
            model_name='like',
            name='post',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='like',
            name='user',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='post',
            name='user',
            field=models.CharField(max_length=30),
        ),
    ]
